language: java

jdk:
  - oraclejdk8

cache:
  directories: 
  - $HOME/.m2
dist: trusty
before_cache:
  - echo "before caching"
  - ls $HOME/
  - ls $HOME/.m2
jobs:
  include:
    - stage: test
      script: mvn verify
    - stage: package
      script: mvn package

after_install:
  - ls -al $HOME/
  - ls -al $HOME/.m2
before_install:
  - ls -al $HOME/
  - ls -al $HOME/.m2
before_script:
  - echo "**************** before script ********************"
