# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Hello
          command: echo "Hello world!"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
#             fallback to using the latest cache if no exact match is found
            - v1-dependencies-
#
      - run: mvn --fail-never dependency:go-offline || true

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Maven
          command: mvn clean verify
  package:
    docker:
      - image: maven:3.6-jdk-8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
#             fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn clean package
      - store_artifacts:
          path: target/hello-world-2.1.4-mule-application-example-1.0.0-SNAPSHOT.zip

workflows:
   two_builds:
     jobs:
       - build
       - package:
          requires:
            - build
   scheduled:
     triggers:
       - schedule:
           cron: "50 2 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
